dist: xenial
language: go
sudo: required

go:
  - "1.12.x"

install:
  - export GO111MODULE=on
  - go mod download
  - php -v
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php composer.phar install --no-interaction --prefer-source
  - find src/ -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - chmod +x bin/rr && bin/rr get-binary

script:
  - go test -race -v -coverprofile=lib.txt -covermode=atomic
  - go test ./util -race -v -coverprofile=util.txt -covermode=atomic
  - go test ./service -race -v -coverprofile=service.txt -covermode=atomic
  - go test ./service/env -race -v -coverprofile=env.txt -covermode=atomic
  - go test ./service/rpc -race -v -coverprofile=rpc.txt -covermode=atomic
  - go test ./service/http -race -v -coverprofile=http.txt -covermode=atomic
  - go test ./service/static -race -v -coverprofile=static.txt -covermode=atomic
  - go test ./service/limit -race -v -coverprofile=limit.txt -covermode=atomic
  - go test ./service/headers -race -v -coverprofile=headers.txt -covermode=atomic
  - go test ./service/metrics -race -v -coverprofile=metrics.txt -covermode=atomic
  - go test ./service/health -race -v -coverprofile=health.txt -covermode=atomic

after_success:
  curl https://codecov.io/bash -o codecov-bash
  chmod +x codecov-bash
  ./codecov-bash -f lib.txt
  ./codecov-bash -f util.txt
  ./codecov-bash -f service.txt
  ./codecov-bash -f env.txt
  ./codecov-bash -f rpc.txt
  ./codecov-bash -f http.txt
  ./codecov-bash -f static.txt
  ./codecov-bash -f limit.txt
  ./codecov-bash -f headers.txt
  ./codecov-bash -f metrics.txt
  ./codecov-bash -f health.txt

jobs:
  include:
    - stage: Test
      env: "PHP=7.1"
      before_install:
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt-get update
        - sudo apt-get install -y php7.1-cli php7.1-curl
        - sudo cp `which php7.1` `which php`
    - stage: Test
      env: "PHP=7.2"
      before_install:
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt-get update
        - sudo apt-get install -y php7.2-cli php7.2-curl
        - sudo cp `which php7.2` `which php`
    - stage: Test
      env: "PHP=7.3"
      before_install:
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt-get update
        - sudo apt-get install -y php7.3-cli php7.3-curl
        - sudo cp `which php7.3` `which php`
    - stage: Test
      env: "PHP=7.4"
      before_install:
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt-get update
        - sudo apt-get install -y php7.4-cli php7.4-curl
        - sudo cp `which php7.4` `which php`