blank_issues_enabled: false

contact_links:
  - name: â“ Start a discussion or ask a question.
    url: https://github.com/spiral/roadrunner/discussions
    about: Please ask and answer questions here.
