name: rr_json_schema_validation

on:
  push:
    branches:
      - master
      - stable
    paths:
      - '.rr*'
      - 'schemas/**'
      - '.github/workflows/schema.yaml'
  pull_request:
    paths:
      - '.rr*'
      - 'schemas/**'
      - '.github/workflows/schema.yaml'

jobs:
  validate-json-schema:
    name: Validate JSON Schema files
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./schemas
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Test Script Dependencies
        run: npm install

      - name: Run Script
        run: node test.js
